export const EMPLOYEE_MESSAGES = {
  INVALID_USER_ID: "Invalid User ID.",
  CREATED: "Employee created successfully.",
  RETRIEVED: "Employee data retrieved successfully.",
  UPDATED: "Employee updated successfully.",
  DELETED: "Employee deleted successfully.",
  ATTENDANCE_RETRIEVED: "Attendance records retrieved successfully.",
  REQUIRED_FIELDS_MISSING: "Requested fields are missing!",
  EMPLOYEE_NOT_FOUND: "Employee not found",
  ATTENDANCE_NOT_FOUND: "Attendance record not found",
  USER_ALREADY_CHECKED_IN: "User has already checked in today.",
  USER_ALREADY_CHECKED_OUT: "User has already checked out today.",
  USER_NOT_CHECKED: "User has not checked in today.",
  CHECK_IN: "Check-in successfully.",
  CHECK_OUT: "Check-out successfully.",
  PROFILE_FETCH_SUCCESS: "Employee profile fetched successfully",
  PROFILE_UPDATE_SUCCESS: "Employee profile updated successfully",
  EMPLOYEE_TYPE_NOT_FOUND: "Employee type not found",
  EMPLOYEE_TYPE_ALREADY_EXISTS: "Employe type already exists",
  EMPLOYEE_TYPE_CREATED: "Employee type created successfully",
  EMPLOYEE_TYPE_UPDATED: "Employee type updated successfully",
  EMPLOYEE_FETCHED: "Employee types fetched successfully",
  LEAVE_TYPE_CREATED: "Leave type created successfully",
  NO_LEAVE_TYPES: "No leave types found. Please create leave types first.",
  LEAVE_TYPE_NOT_FOUND: "Leave type not assigned to this employee type.",
  LEAVE_TYPE_ALREADY_EXIST: "Leave type already exist",
  LEAVE_TYPE_UPDATED: "Leave type updated successfully",
  LEAVE_TYPE_FETCHED: "Leave types fetched successfully",
  LEAVE_BALANCE_UPDATED: "Leave balance updated successfully.",
  LEAVE_BALANCE_NOT_FOUND: "Leave balance not found",
  INVALID_LEAVE_COUNT: "total_leaves must be a positive number",
  NO_LEAVES_FOUND: "No Leaves found",
  LEAVES_FETCHED: "Leaves fetched successfully",
  USED_LEAVES_EXCEED: "Used leaves cannot exceed total allocated leaves.",
  USED_LEAVES_UPDATED: "Used leaves updated successfully.",
  LEAVE_BALANCE_CREATED: "Leave balance crated successfully",
  LEAVE_BALANCE_ALREADY_EXISTS:
    "Leave balance already exists for this employee type and leave type.",
  LEAVE_BALANCE_FETCHED: "Leave balance fetched successfully.",
  LEAVE_BALANCE_ERROR: "Failed to retrieve leave balance.",
  LEAVE_REQUEST_NOT_FOUND: "Leave request not found",
  LEAVE_EDIT_DENIED: "You can only edit or cancel request with Pending status",
  LEAVE_CANCELLED: "Leave request cancelled successfully",
  LEAVE_UPDATED: "Leave request updated successfully",
  LEAVE_UPDATE_ERROR: "Server error while updating leave request.",
  LEAVE_TYPE_NOT_ASSIGNED:
    "This leave type is not assigned to your employee type.",
  INSUFFICIENT_BALANCE: (available, requested) =>
    `Insufficient leave balance. Available: ${available}, Requested: ${requested}`,
  OVERLAPPING_LEAVE: (start, end) =>
    `You already have an approved/pending leave from ${start} to ${end}. Please choose different dates.`,
  LEAVE_SUBMITTED:
    "Leave request submitted successfully. Waiting for HR approval.",
  INVALID_DATE_RANGE: "Start date must be before or equal to end date",
  INVALID_HALF_DAY: "Half-day leave must have the same start and end date.",
    CONFIRM_PASSWORD_NOT_MATCH: "Password and Confirm Password do not match.",
  UNIQUE_EMPLOYEE_CODE: "Employee code must be unique.",
  INVALID_JOINING_DATE_FORMAT: "Invalid joining date format. Use 'YYYY-MM-DD' or 'DD-MM-YYYY'.",
  INVALID_LAST_WORKING_DATE_FORMAT: "Invalid last working date format. Use 'YYYY-MM-DD' or 'DD-MM-YYYY'.",
  INVALID_EMPLOYEE_TYPE_ID:  "Invalid employee_type ID.",
   EMPLOYEE_NOT_FOUND: "Employee not found",
   INVALID_SESSION: "Invalid session index",
   ATTENDANCE_ADDED: "Attendance added successfully",
   ATTENDANCE_UPDATED: "Attendance updated successfully",
   CHECK_IN_TIME_MUST_FIRST: "Check-out time must be after check-in time",
   EMPLOYEE_CODE_ALREADY_EXISTS: "Employee code already exists",
   INVALID_LEAVE_TYPE: "Invalid leave type"
};
