import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import App from "./app"; // Import the App component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HRM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <App>{children}</App> {/* Pass children to App */}
      </body>
    </html>
  );
}
