export const COMMON_MESSAGES = {
    SUCCESS: "Request successful.",
    SERVER_ERROR: "Internal Server Error.",
    INVALID_INPUT: "Invalid Input Data.",
    UNAUTHORIZED: "Access denied.",
    INVALID_PAGE_AND_LIMIT: "Invalid page or limit parameters.",
    USER_NOT_FOUND: "User Not Found.",
    NOT_FOUND: "Resource not found.",
    EMAIL_REQUIRED: "Email is required.",
    EMAIL_ALREADY_EXIST: "Email already exists.",
    USER_NOT_EXIST: "User Not Found.",
    USER_EXISTS: "User already exists.",
    INVALID_EMAIL: "Invalid email address.",
    NO_TOKEN: "Access denied. You do not have the required permissions to access this resource.",
    INVALID_TOKEN: "Authentication error. The provided token is invalid or has expired. Please log in again to obtain a valid token.",
    INVALID_PASSWORD: "Access denied. The password is incorrect. Please try again.",
    LOGGED_IN: "Login successfully.",
    PASSWORD_RESET_LINK: "Password reset link sent to your email",
    NEW_PASSWORD: "New password must be different from the previous password",
    MISSING_FIELDS: "All fields are required",
    NO_LEAVE_RECORD: "No leave records found",
    ALL_FIELDS_REQUIRED: "All fields are required",
    OLD_PASSWORD_INCORRECT: "Old password is incorrect",
    PASSWORD_CHANGED: "Password changed successfully",
    INVALID_UPDATE_FIELDS: "Invalid fields for update",
  };
  